theme = "blowfish"
baseURL = "https://blog.thedojo.mx/"
languageCode = "es"
defaultContentLanguage = "es"
title = "The Dojo MX Blog"
publishDir = "docs"

enableRobotsTXT = true
summaryLength = 30
enableEmoji = true

[pagination]
pagerSize = 25

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
posts = "/:year/:month/:day/:slug/"

# Google Analytics
googleAnalytics = "UA-127437335-2"

[services]
  [services.googleAnalytics]
    ID = "UA-127437335-2"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
